### ISSUE TITLE
Add monitoring Covid-19 in Chiang Mai

### ISSUE THREAD

**Issue by jedsada-gh** [COVID19-TCDC/Awesome-Thai-CoVid#10]
สวัสดีครับ ทาง Developer ที่อยู่ในจังหวัดเชียงใหม่ได้รวมตัวกันพัฒนาระบบ Monitoring โรค Covid-19 ในจังหวัดเชียงใหม่ขึ้นมานะครับ เพื่อเป็นอีกช่องทางเลือกสำหรับการเข้าถึงข้อมูลนะครับ

https://covid-19-cnx.web.app/

<img width="1308" alt="Screen Shot 2563-04-03 at 19 06 17" src="https://user-images.githubusercontent.com/24611167/78358946-43dd7d80-75de-11ea-92a9-59be57a78bba.png">

<img width="1253" alt="Screen Shot 2563-04-03 at 19 06 27" src="https://user-images.githubusercontent.com/24611167/78358953-463fd780-75de-11ea-9665-d4427ac3147e.png">

**Comment by ninyawee** [comment]
ได้ครับเดี๋ยวเพิ่มให้นะครับ
