### ISSUE TITLE
YouTube videos related to viruses and pandemics

### ISSUE THREAD

**Issue by p16i** [COVID19-TCDC/Awesome-Thai-CoVid#6]
สวัสดีครับ

ส่วนตัวคิดว่านอกจากเรื่องตัวเลขแล้ว ข้อมูลพื้นฐานต่างๆ เกี่ยวกับระบาดวิทยาและชีววิทยาของไวรัสก็น่าจะเป็นเนื้อหาที่มีประโยชน์ เราได้นั่งรวมๆเนื้อหามาจาก YouTube และส่วนใหญ่มีคำแปลแล้ว เราอาจจะทำเป็น Playlist บน YouTube ให้คนที่สนใจเข้าไปนั่งดู 

## ด้านชีววิทยาของไวรัส

[โคโรน่าไวรัสคืออะไร และอะไรที่เราควรทำ (The Coronavirus Explained & What You Should Do)](https://www.youtube.com/watch?v=BtN-goy9VOY)

[วัคซีนทำงานอย่างไร (How do vaccines work?)](https://www.youtube.com/watch?v=rb7TVW77ZCs)

[เกิดอะไรขึ้นในร่างกายของเราถ้าเราได้รับโคโรน่าไวรัส (What Actually Happens If You Get Coronavirus?)](https://www.youtube.com/watch?v=OTYfke545vIhttps://www.youtube.com/watch?v=OTYfke545vI) (คำแปลอัตโนมัติ)

[โรคไวรัสโคโรน่า 2019 (Covid-19) ส่งผลกระทบต่อร่างกายเราอย่างไร (How Does Covid-19 Affect the Body?)](https://www.youtube.com/watch?v=Xj1nUFFVK1E)

### ไม่มีคำแปล

[ไวรัสคืออะไร (Viruses)](https://www.youtube.com/watch?v=8FqlTslU22s)

[ไวรัสถ่ายทอดข้ามสายพันธ์ุจากสัตว์มามนุษย์อย่างไร (How do viruses jump from animals to humans?)](https://www.youtube.com/watch?v=xjcsrU-ZmgY)

[ไวรัสประเภทใหม่มาจากไหน (Where Do New Viruses Come From?)](https://www.youtube.com/watch?v=NJLXdsO1GBI)

[โรคหวัดระบาด! ไวรัสเข้าโจมตีร่างกายเราได้อย่างไร (Flu Attack! How A Virus Invades Your Body)](https://www.youtube.com/watch?v=Rpj0emEGShQ)

### ไม่มีคำแปล

[โรคปอดบวม (Pneumonia)](https://www.youtube.com/watch?v=sB5XW4exTFE)

[สบู่ป้องกันไวรัสได้อย่างไร (How soap kills the coronavirus)](https://www.youtube.com/watch?v=-LKVUarhtvE)

## ด้านพันธุกรรม

[การทำงานของชีววิทยาระดับโมเลกุลภายในร่างกาย (Animations of unseeable biology)](//www.youtube.com/watch?v=WFCvkkDSfIU&t=5s)

### ไม่มีคำแปล

[ไวรัสขยายพันธ์ุได้อย่างไร (How do Viruses Reproduce?)](https://www.youtube.com/watch?v=QHHrph7zDLw)

## ด้านสถิติและระบาดวิทยา

[กราฟนี้หมายความว่าอะไรสำหรับสำหรับโรคระบาด Covid-19 What This Chart Actually Means for COVID-19](https://www.youtube.com/watch?v=fgBla7RepXU) 

## การระบาดของไวรัสครั้งก่อนๆ
กำลังรวบรวม

Ebola
Spanish Flu

**Comment by p16i** [comment]
@unnawut iirc, you were part of TED's translation team. Do you have any suggestion or advice on translating these videos?

**Comment by ninyawee** [comment]
ได้ครับ เดี๋ยวเพิ่มเข้าส่วน resources

**Comment by ninyawee** [comment]
ถ้า final แล้วบอกผมนะครับ

**Comment by unnawut** [comment]
> @unnawut iirc, you were part of TED's translation team. Do you have any suggestion or advice on translating these videos?

ของ TED เค้าจะใช้ระบบชื่อว่า Amara ครับ จะเป็น UI สำหรับแปลซับโดยเฉพาะ พอแปลเสร็จ ผ่านขั้นตอนที่ TED ตั้งไว้ครบ มันจะถูกยิงไปที่ Youtube โดยตรงเลย ความสะดวกของ Amara คือสามารถใช้ UI ของเค้าในการเลื่อนวาง timing และกด play เพื่อเช็คได้เลย ถ้าทำใน text editor ฯลฯ จะยากตรงนี้ครับ

ถ้าเป็นวีดีโอของ TED คนที่สนใจแปลสามารถสมัครได้ที่ https://www.ted.com/participate/translate/get-started แล้วก็ไปตามขั้นตอนของ TED เลยครับ

-----

ทีนี้ สำหรับช่องยูทูบอื่นๆ สามารถใช้ Amara ได้เหมือนกัน แต่จะติดตรงที่ว่าถ้าเจ้าของวีดีโอไม่ได้ผูกกับ Amara ไว้ เจ้าของวีดีโอต้องอัพซับฯ ขึ้นยูทูบเอง จึงควรติดต่อนัดแนะกับเจ้าของวีดีโอก่อน พอนัดแนะเรียบร้อยอาจจะใช้ Amara หรือโปรแกรมทำซับฯอื่นๆ ตามสะดวก (แต่ไม่แนะนำให้แปลใส่ google docs, text editor อะไรพวกนี้ครับ คนอัพซับต้องไปจัด time sequence เอง เกลาคำให้เข้า time sequence งานจะโหลดมากๆๆๆ)

รายละเอียด Amara ตามนี้ครับ https://amara.org/en/subtitling-platform/#free-platform

**Comment by unnawut** [comment]
สรุปคร่าวๆคือ

- วีดีโอของ TED ให้ไปสมัครแปลที่ https://www.ted.com/participate/translate/get-started

- วีดีโออื่นๆ ให้ทำดังนี้

    1. สอบถามเจ้าของวีดีโอ ว่าสนใจให้แปลซับไหม ถ้าแปลเสร็จแล้วรบกวนอัพใส่ระบบให้หน่อยได้ไหม
    2. ถ้าเจ้าของวีดีโอตอบตกลง อย่าแปลลง text/document editor เช่น Notepad, Microsoft Word, Google Docs ให้แปลด้วยโปรแกรมแปลซับ เพื่อให้ได้[ไฟล์ .srt](https://matroska.org/technical/specs/subtitles/srt.html) ออกมา แนะนำโปรแกรมฟรีและออนไลน์ชื่อ [Amara](https://amara.org/en/subtitling-platform/#free-platform) ตัวเดียวกับที่ TED ใช้
    3. ส่งกลับให้เจ้าของวีดีโอเพื่ออัพเข้าระบบที่วางวีดีโอไว้

**Comment by ninyawee** [comment]
เป็นไงบ้างครับ มีอัพเดทไหมครับ

**Comment by p16i** [comment]
@CircleOnCircles ตอนนี้ผมกับเพื่อนกำลังแปลบทความนี้กันอยู่
https://medium.com/nightingale/ten-considerations-before-you-create-another-chart-about-covid-19-27d3bd691be8

เลยไม่ได้ดูเรื่องตัว VDO เท่าไหร่ ลองดูๆของไทยเหมือนเริ่มมีเยอะแล้ว เลยคิดว่าเราอาจจะไม่ต้องทำแล้วมั้ง?

**Comment by ninyawee** [comment]
อ่านแล้วประทับใจครับ ดีมากครับ จะรออ่านผลงานนะครับ

ส่วนถ้ายังไม่มั่นใจเรื่องลงวิดีโอ ผมปิด issue ไปก่อน แล้วถ้ายังทำเดี๋ยวผม reopen ให้นะครับ
